export const landingCopy = {
  uk: {
    navCollection: 'Можливості',
    navAnalytics: 'Аналітика',
    catalog: 'Каталог',
    login: 'Увійти',
    eyebrow: 'ДЛЯ ТИХ, ХТО КОЛЕКЦІОНУЄ',
    title: 'Кожна монета\nна своєму місці.',
    intro:
      'Ваша колекція заслуговує на більше, ніж список. Зберігайте кожен екземпляр, враховуйте всі витрати й бачте, як зростає ваше захоплення.',
    start: 'Створити колекцію',
    open: 'До моєї колекції',
    explore: 'Переглянути каталог',
    heroNotes: ['Монети з каталогу та власні', 'Кожен екземпляр окремо'],
    demo: 'Приклад колекції',
    coin: 'Сила кохання',
    coinMeta: 'Україна · 2025 · 10 гривень',
    silver: 'Срібло 925',
    weight: '31,1 г',
    inCollection: 'У колекції',
    instances: 'Мої екземпляри',
    details: 'Про монету',
    condition: 'Стан',
    storage: 'Місце зберігання',
    price: 'Ціна купівлі',
    estimatedPrice: 'Оціночна ціна',
    perCoin: 'за монету',
    investedTotal: 'Вкладено загалом',
    includingDelivery: 'з них доставка —',
    estimatedTotal: 'Поточна оцінка',
    specimensCount: 'екземпляри',
    valueChange: 'Зміна вартості',
    specimen: 'Екземпляр',
    fullCost: 'Повна ціна',
    demoFinancialNote: 'Приклад обліку: ціни та покупки демонстраційні.',
    album: 'Альбом №1 · комірка 12',
    capsule: 'Капсула · сейф',
    note: 'Один випуск. Кожен екземпляр — зі своєю історією.',
    coinDescription:
      'Пам’ятна монета про почуття, що поєднує. Срібло, локальна позолота та хвилі, що розходяться від золотого серця.',
    coinLink: 'Відкрити монету в каталозі',
    attribution: 'Фото монети: Національний банк України',
    featureTitles: ['Колекція без обмежень', 'Усі витрати на місці', 'Почніть свою колекцію'],
    featureTexts: [
      'Усі ваші монети, покупки й оцінка. Зручний пошук і фільтри для всієї колекції.',
      'Ціна монети, доставка, футляр. Враховуйте те, що важливо вам.',
      'Додайте першу монету — з каталогу або власну.',
    ],
    collectionTitle: 'За вашими правилами.\nДо останньої монети.',
    collectionText:
      'Усі ваші монети, покупки й поточна оцінка — в одному місці. Знаходьте потрібне та дивіться підсумки саме для обраної частини колекції.',
    collectionBullets: [
      'Шукайте за назвою. Фільтруйте за країною, серією, періодом, металом і станом.',
      'Кількість монет, витрати, оцінка й різниця перераховуються за вашими фільтрами.',
      'Перемикайте картки й таблицю. Сортуйте за датою випуску, назвою або сумою покупки.',
    ],
    tryFilters: 'Спробуйте фільтри у прикладі',
    myCoins: 'Мої монети',
    search: 'Знайти монету…',
    demoSeries: ['Інші монети', 'Збройні Сили України', 'Видатні особистості України'],
    demoNames: ['Сила кохання', 'Десантно-штурмові війська Збройних Сил України', 'Леся Українка'],
    demoMetas: ['2025 · 10 гривень', '2021 · 10 гривень', '1996 · 200 000 карбованців'],
    empty: 'За цими фільтрами монет немає.',
    reset: 'Скинути фільтри',
    completeness: 'Комплектність серії',
    series: 'Моя добірка пам’ятних монет',
    collected: 'зібрано',
    missing: 'Залишилося знайти 6 монет',
    expensesTitle: 'Знайте ціну\nсвого захоплення.',
    expensesText:
      'Покупки монет, доставка, альбоми й капсули — бачте, скільки насправді витрачаєте на захоплення. Усі витрати зібрані в одному журналі.',
    expensesBullets: [
      'Покупки потрапляють у журнал автоматично. Доставку й інші витрати додавайте окремо або разом із монетою.',
      'Переглядайте графіки за місяць, квартал, пів року чи рік — або задавайте власні дати.',
      'Фільтруйте записи за категорією. Загальні підсумки показують витрати на монети, супутні витрати та суму за місяць.',
    ],
    tryPeriod: 'Оберіть період графіка або категорію в журналі',
    finalEyebrow: 'КОЖНА КОЛЕКЦІЯ ПОЧИНАЄТЬСЯ З ОДНІЄЇ МОНЕТИ',
    finalTitle: 'Дайте своїй колекції дім.',
    finalText: 'Зберігайте історію. Помічайте деталі. Колекціонуйте із задоволенням.',
    footer: 'З турботою про колекціонерів.',
    privacy: 'Конфіденційність',
    terms: 'Умови користування',
  },
  en: {
    navCollection: 'Features',
    navAnalytics: 'Analytics',
    catalog: 'Catalog',
    login: 'Sign in',
    eyebrow: 'FOR THE LOVE OF COLLECTING',
    title: 'Every coin\nin its place.',
    intro:
      'Your collection deserves more than a list. Keep every specimen, account for every expense, and see your passion grow.',
    start: 'Start your collection',
    open: 'Open my collection',
    explore: 'Explore the catalog',
    heroNotes: ['Catalog coins and your own finds', 'Every specimen individually'],
    demo: 'Example collection',
    coin: 'The Power of Love',
    coinMeta: 'Ukraine · 2025 · 10 hryvnias',
    silver: '925 silver',
    weight: '31.1 g',
    inCollection: 'In collection',
    instances: 'My specimens',
    details: 'About the coin',
    condition: 'Grade',
    storage: 'Storage location',
    price: 'Purchase price',
    estimatedPrice: 'Estimated price',
    perCoin: 'per coin',
    investedTotal: 'Total invested',
    includingDelivery: 'shipping included —',
    estimatedTotal: 'Current estimate',
    specimensCount: 'specimens',
    valueChange: 'Value change',
    specimen: 'Specimen',
    fullCost: 'Full cost',
    demoFinancialNote: 'Bookkeeping example: prices and purchases are illustrative.',
    album: 'Album #1 · slot 12',
    capsule: 'Capsule · safe',
    note: 'One issue. A different story for every specimen.',
    coinDescription:
      'A commemorative coin celebrating a feeling that connects us. Silver, selective gilding, and ripples radiating from a golden heart.',
    coinLink: 'View this coin in the catalog',
    attribution: 'Coin photos: National Bank of Ukraine',
    featureTitles: [
      'A collection without limits',
      'Every expense accounted for',
      'Start your collection',
    ],
    featureTexts: [
      'Your coins, purchases, and valuations. Search and filters for your whole collection.',
      'The coin, shipping, a display case. Track what matters to you.',
      'Add your first coin — from the catalog or your own finds.',
    ],
    collectionTitle: 'Your collection. Your rules.\nEvery last coin.',
    collectionText:
      'Your coins, purchases, and current valuations in one place. Find what you need and see totals for the part of your collection you select.',
    collectionBullets: [
      'Search by name. Filter by country, series, period, metal, and grade.',
      'Coin counts, spending, valuations, and differences update with your filters.',
      'Switch between cards and a table. Sort by issue date, name, or purchase amount.',
    ],
    tryFilters: 'Try the filters in this example',
    myCoins: 'My coins',
    search: 'Find a coin…',
    demoSeries: ['Other coins', 'Ukraine’s Armed Forces', 'Outstanding Personalities of Ukraine'],
    demoNames: [
      'The Power of Love',
      'The Airborne Force of Ukraine’s Armed Forces',
      'Lesya Ukrainka',
    ],
    demoMetas: ['2025 · 10 hryvnias', '2021 · 10 hryvnias', '1996 · 200,000 karbovantsi'],
    empty: 'No coins match these filters.',
    reset: 'Reset filters',
    completeness: 'Series completeness',
    series: 'My commemorative selection',
    collected: 'collected',
    missing: '6 more coins to find',
    expensesTitle: 'Know the cost\nof your passion.',
    expensesText:
      'Coin purchases, shipping, albums and capsules — see what your hobby really costs. Keep every expense in one journal.',
    expensesBullets: [
      'Purchases appear automatically. Add shipping and other expenses separately or alongside a coin.',
      'Explore charts for one, three or six months, a year, or your own date range.',
      'Filter journal entries by category. Summary tiles show coin spending, related expenses and the monthly total.',
    ],
    tryPeriod: 'Choose a chart period or a journal category',
    finalEyebrow: 'EVERY COLLECTION BEGINS WITH A SINGLE COIN',
    finalTitle: 'Give your collection a home.',
    finalText: 'Keep the stories. Notice the details. Enjoy collecting.',
    footer: 'Made with collectors in mind.',
    privacy: 'Privacy',
    terms: 'Terms of use',
  },
};

export type LandingCopy = (typeof landingCopy)['uk'];
