#!/usr/bin/env python3
"""Keep docs/ and the code in step.

One script, three entry points, no dependencies beyond Python 3.11+:

  commit-msg <file>   git commit-msg hook (.githooks/commit-msg). Blocks a commit
                      that changes code mapped to a document in docs/doc-map.toml
                      without staging that document, unless the message carries
                      the trailer "Docs: not needed" (optionally with a reason).
                      Also runs the reference checks on the staged files.
  refs                CI: reference checks over every tracked file.
  table [--check]     Regenerates the "Which document to update" table in
                      docs/README.md from docs/doc-map.toml (--check: fail if stale).

Reference checks:
  * every cited `docs/<name>.md` exists;
  * every cited section — docs/<name>.md, "Heading" — is a heading in that file
    (case-insensitive prefix match, so "Overview" matches 'Overview ("Огляд")');
  * every BR-N cited anywhere is a heading in docs/business-rules.md;
  * no Russian-only letters (U+044B, U+044D, U+044A, U+0451 and capitals — the
    ones Ukrainian lacks) outside the allowlist in doc-map.toml.
    Ukrainian quoted UI labels stay legal; the check can't tell Russian words
    without those letters, so it catches the common case, not all of them.
"""

from __future__ import annotations

import re
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
MAP_FILE = DOCS / "doc-map.toml"
README = DOCS / "README.md"
TABLE_BEGIN = "<!-- doc-map:begin (generated by tools/docs_check.py table) -->"
TABLE_END = "<!-- doc-map:end -->"
TRAILER_RE = re.compile(r"^Docs:\s*not needed\b", re.IGNORECASE | re.MULTILINE)
RUSSIAN_RE = re.compile("[\u044b\u044d\u044a\u0451\u042b\u042d\u042a\u0401]")
DOC_REF_RE = re.compile(r"(?<![\w/.-])(?:\.\./)?docs/([a-z0-9][a-z0-9-]*)\.md")
SECTION_REF_RE = re.compile(
    r"(?<![\w/.-])(?:\.\./)?docs/([a-z0-9][a-z0-9-]*)\.md[`'\"]?,\s*(?:#\s*)?\"([^\"\n]{2,80})\""
)
SIBLING_REF_RE = re.compile(r"`([a-z0-9][a-z0-9-]*)\.md`(?:,\s*\"([^\"\n]{2,80})\")?")
BR_RE = re.compile(r"\bBR-(\d+a?)\b")
HEADING_RE = re.compile(r"^#{1,6}\s+(.+?)\s*$", re.MULTILINE)
BR_HEADING_RE = re.compile(r"^##\s+BR-(\d+a?)\.", re.MULTILINE)


@dataclass(frozen=True)
class Rule:
    doc: str
    paths: tuple[str, ...]
    note: str


def load_map() -> tuple[list[Rule], list[str], list[str]]:
    data = tomllib.loads(MAP_FILE.read_text(encoding="utf-8"))
    rules = [
        Rule(doc=r["doc"], paths=tuple(r["paths"]), note=r.get("note", "")) for r in data["rule"]
    ]
    return rules, data.get("russian_allowed", []), data.get("skip_scan", [])


def glob_to_regex(pattern: str) -> re.Pattern[str]:
    out = []
    i = 0
    while i < len(pattern):
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif pattern[i] == "*":
            out.append("[^/]*")
            i += 1
        else:
            out.append(re.escape(pattern[i]))
            i += 1
    return re.compile("".join(out) + r"\Z")


def matches(path: str, patterns: list[str] | tuple[str, ...]) -> bool:
    return any(glob_to_regex(p).match(path) for p in patterns)


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], cwd=ROOT, check=True, capture_output=True, text=True
    ).stdout


def is_text(path: str) -> bool:
    return not path.endswith(
        (".png", ".jpg", ".jpeg", ".webp", ".gif", ".ico", ".woff", ".woff2", ".pdf", ".lock")
    )


# --- reference checks ---------------------------------------------------------


def headings(doc: str) -> list[str] | None:
    path = DOCS / f"{doc}.md"
    if not path.exists():
        return None
    return [h.replace("`", "").strip().lower() for h in HEADING_RE.findall(path.read_text("utf-8"))]


def business_rule_ids() -> set[str]:
    return set(BR_HEADING_RE.findall((DOCS / "business-rules.md").read_text("utf-8")))


def check_text(path: str, text: str, russian_allowed: list[str]) -> list[str]:
    problems: list[str] = []
    br_ids = business_rule_ids()
    in_docs = path.startswith("docs/") and path.endswith(".md")

    def line_of(pos: int) -> int:
        return text.count("\n", 0, pos) + 1

    for m in DOC_REF_RE.finditer(text):
        if headings(m.group(1)) is None:
            problems.append(f"{path}:{line_of(m.start())}: docs/{m.group(1)}.md does not exist")
    section_refs = [(m, m.group(1), m.group(2)) for m in SECTION_REF_RE.finditer(text)]
    if in_docs:
        for m in SIBLING_REF_RE.finditer(text):
            doc = m.group(1)
            if (ROOT / f"{doc}.md").exists() or doc == "readme":
                continue
            if headings(doc) is None:
                problems.append(f"{path}:{line_of(m.start())}: {doc}.md does not exist in docs/")
            elif m.group(2):
                section_refs.append((m, doc, m.group(2)))
    for m, doc, section in section_refs:
        known = headings(doc)
        wanted = section.replace("`", "").strip().lower()
        if known is not None and not any(h.startswith(wanted) for h in known):
            problems.append(
                f'{path}:{line_of(m.start())}: docs/{doc}.md has no section "{section}"'
            )
    for m in BR_RE.finditer(text):
        if m.group(1) not in br_ids:
            problems.append(f"{path}:{line_of(m.start())}: BR-{m.group(1)} is not in business-rules.md")
    if not matches(path, russian_allowed):
        for m in RUSSIAN_RE.finditer(text):
            problems.append(f"{path}:{line_of(m.start())}: Russian letter {m.group(0)!r}")
            break
    return problems


def check_files(files: list[tuple[str, str]]) -> list[str]:
    _, russian_allowed, skip = load_map()
    problems: list[str] = []
    for path, text in files:
        if is_text(path) and not matches(path, skip):
            problems.extend(check_text(path, text, russian_allowed))
    return problems


def tracked_files() -> list[tuple[str, str]]:
    out = []
    for path in git("ls-files").splitlines():
        full = ROOT / path
        if full.is_file() and is_text(path):
            try:
                out.append((path, full.read_text(encoding="utf-8")))
            except UnicodeDecodeError:
                continue
    return out


def staged_files() -> list[tuple[str, str]]:
    out = []
    for path in git("diff", "--cached", "--name-only", "--diff-filter=ACMR").splitlines():
        if not is_text(path):
            continue
        try:
            out.append((path, git("show", f":{path}")))
        except (subprocess.CalledProcessError, UnicodeDecodeError):
            continue
    return out


# --- commands -----------------------------------------------------------------


def cmd_refs() -> int:
    problems = check_files(tracked_files())
    for p in problems:
        print(p)
    if problems:
        print(f"\n{len(problems)} documentation problem(s). See docs/README.md, 'Writing docs'.")
        return 1
    print("docs references OK")
    return 0


def banner(lines: list[str]) -> str:
    bar = "━" * 60
    return "\n".join([bar, "⚠️  DOCS UPDATE REQUIRED", bar, *lines, bar])


def cmd_commit_msg(msg_file: str) -> int:
    if (ROOT / ".git" / "MERGE_HEAD").exists():
        return 0
    message = Path(msg_file).read_text(encoding="utf-8")
    body = "\n".join(line for line in message.splitlines() if not line.startswith("#"))
    if body.startswith(("fixup!", "squash!", "Revert ")):
        return 0

    failed = False
    if RUSSIAN_RE.search(body):
        print("Commit message contains Russian — commit messages are English (AGENTS.md).")
        failed = True

    staged = staged_files()
    for p in check_files(staged):
        print(p)
        failed = True

    rules, _, _ = load_map()
    staged_paths = set(git("diff", "--cached", "--name-only").splitlines())
    missing: dict[str, list[str]] = {}
    for path in sorted(staged_paths):
        for rule in rules:
            if matches(path, rule.paths) and rule.doc not in staged_paths:
                missing.setdefault(rule.doc, []).append(path)
    if missing and not TRAILER_RE.search(body):
        lines = []
        for doc, paths in missing.items():
            shown = ", ".join(paths[:4]) + (f" (+{len(paths) - 4} more)" if len(paths) > 4 else "")
            lines.append(f"You changed: {shown}")
            lines.append(f"Update:      {doc}")
        lines += [
            "",
            "Update and stage the document(s) in this commit, or — if behavior,",
            "API, schema, UI and infra are unchanged — add the trailer:",
            "    Docs: not needed (<why>)",
        ]
        print(banner(lines))
        failed = True
    return 1 if failed else 0


def render_table(rules: list[Rule]) -> str:
    rows = ["| You changed | Update |", "|---|---|"]
    for rule in rules:
        what = rule.note or ", ".join(f"`{p}`" for p in rule.paths)
        rows.append(f"| {what} | `{Path(rule.doc).name}` |")
    return "\n".join(rows)


def cmd_table(check: bool) -> int:
    rules, _, _ = load_map()
    text = README.read_text(encoding="utf-8")
    start, end = text.index(TABLE_BEGIN), text.index(TABLE_END)
    new = text[: start + len(TABLE_BEGIN)] + "\n" + render_table(rules) + "\n" + text[end:]
    if new == text:
        return 0
    if check:
        print("docs/README.md table is stale: run `python3 tools/docs_check.py table`.")
        return 1
    README.write_text(new, encoding="utf-8")
    print("docs/README.md table regenerated")
    return 0


def main(argv: list[str]) -> int:
    if len(argv) >= 2 and argv[0] == "commit-msg":
        return cmd_commit_msg(argv[1])
    if argv[:1] == ["refs"]:
        return cmd_refs()
    if argv[:1] == ["table"]:
        return cmd_table(check="--check" in argv)
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
